//------------------LOCALHOST 3000 ROUTES:---------------------------

// All Contacts
GET http://localhost:3000/contacts
###
// Get Contact by ID
GET http://localhost:3000/contacts/650dc6a1c4bfced2bd80717d
###
GET http://localhost:3000/contacts/650dc6a1c4bfced2bd80717e
###
GET http://localhost:3000/contacts/650dc6a1c4bfced2bd80717f
###
//Post a new contact
POST http://localhost:3000/contacts HTTP/1.1
Content-Type: application/json

{
  "firstName": "Michi",
  "lastName": "Miaw",
  "email": "example@catmail.com",
  "favoriteColor": "none",
  "birthday": "May 27th "
}
###
// Update Contact by ID
PUT http://localhost:3000/contacts/65183f27db10bd7a3bb45b2e HTTP/1.1
Content-Type: application/json

{
    "firstName": "Michi",
    "lastName": "Miaw",
    "email": "example@catmail.com",
    "favoriteColor": "green",
    "birthday": "Feb 18th"
}
###
//Delete Contact by ID
DELETE http://localhost:3000/contacts/65183f27db10bd7a3bb45b2e HTTP/1.1
###


//----------------------PRODUCTION DEPLOYS----------------------------

GET https://cse341-l1-rc.onrender.com/contacts
###
GET https://cse341-l1-rc.onrender.com/contacts/650dc6a1c4bfced2bd80717d
###
GET https://cse341-l1-rc.onrender.com/contacts/650dc6a1c4bfced2bd80717e
###
GET https://cse341-l1-rc.onrender.com/contacts/650dc6a1c4bfced2bd80717f
###

//Post a new contact
POST https://cse341-l1-rc.onrender.com/contacts HTTP/1.1
Content-Type: application/json

{
  "firstName": "Michi",
  "lastName": "Miaw",
  "email": "example@catmail.com",
  "favoriteColor": "none",
  "birthday": "May 27th "
}
###
// Update Contact by ID
PUT https://cse341-l1-rc.onrender.com/contacts/651848567b163a634e8b59f9 HTTP/1.1
Content-Type: application/json

{
    "firstName": "Michi",
    "lastName": "Miaw",
    "email": "imaflufflycat@catmail.com",
    "favoriteColor": "green",
    "birthday": "Feb 18th"
}
###
//Delete Contact by ID
DELETE https://cse341-l1-rc.onrender.com/contacts/651848567b163a634e8b59f9 HTTP/1.1
###

